### ISSUE TITLE
Error Python in QGIS 3.34.7

### ISSUE THREAD

**Issue by Joseph-ut2j** [esc-unil/Visualist#16]
2024-06-06T11:07:21     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/joseph.buosi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\__init__.py", line 37, in classFactory
              from .visualist_main import VisualistPlugin
              File "C:\PROGRA~1/QGIS33~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/joseph.buosi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\visualist_main.py", line 41, in 
              from .visualist_provider import VisualistProvider
              File "C:\PROGRA~1/QGIS33~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/joseph.buosi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\visualist_provider.py", line 43, in 
              from .Lisa import LocalIndicatorSpatialA
              File "C:\PROGRA~1/QGIS33~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/joseph.buosi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\Lisa.py", line 34, in 
              from . import pysal
              File "C:\PROGRA~1/QGIS33~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/joseph.buosi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\__init__.py", line 57, in 
              from . import lib
              File "C:\PROGRA~1/QGIS33~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/joseph.buosi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\__init__.py", line 23, in 
              from . import cg
              File "C:\PROGRA~1/QGIS33~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/joseph.buosi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\cg\__init__.py", line 7, in 
              from .kdtree import *
              File "C:\PROGRA~1/QGIS33~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/joseph.buosi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\cg\kdtree.py", line 9, in 
              from scipy import inf
             ImportError: cannot import name 'inf' from 'scipy' (C:\PROGRA~1\QGIS33~1.7\apps\Python312\Lib\site-packages\scipy\__init__.py)

**Comment by Joseph-ut2j** [comment]
The problem with this extension appeared with versions 3.34.6 and 3.34.7
However, the extension works fine with version 3.34.4

**Comment by qrossy** [comment]
thank you for the feedback. I'll try to find a solution

**Comment by qrossy** [comment]
A new version 0.8.1 has been submited to the QGIS repository: should work on QGIS 3.34.7 LTR

**Comment by Joseph-ut2j** [comment]
Dear Quentin,

Thank you very much for your responsiveness.
My teaching colleagues and I will be testing your new version. 
We'll be integrating your extension as part of our geomatics training courses for our bachelor's and master's degrees.
Best regards

June 10, 2024 at 3:39:41 PM CEST Quentin Rossy ***@***.***> wrote:

A new version 0.8.1 has been submited to the QGIS repository: should work on QGIS 3.34.7 LTR
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Joseph BUOSI
Département de Géographie - UFR SES
Bat. Olympe de Gouges - Bureau GS 011
+33 5 61 50 43 89
Université de Toulouse - Jean Jaurès
5 allées Antonio Machado
31058 TOULOUSE Cedex 9
